/**
 * Human-readable ABI fragments for ethers.js.
 *
 * These are hand-written from `contracts/*.sol` rather than generated by
 * `hardhat compile`, because this sandbox has no network access to install
 * hardhat's dependencies (see CONTRACTS.md). Each fragment mirrors the
 * exact function/event signature in the Solidity source it's named after —
 * once you run `npx hardhat compile` for real, you can swap these for the
 * generated JSON from `artifacts/contracts/**\/*.json` with no other code
 * changes, since `src/lib/contracts.ts` only cares about the ABI shape.
 */

export const AGENT_NFT_ABI = [
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function tokenURI(uint256 tokenId) view returns (string)",
  "function minter() view returns (address)",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
] as const;

export const AGENT_REGISTRY_ABI = [
  "function register(string ipfsHash, string category) returns (uint256 agentId)",
  "function updateMetadata(uint256 agentId, string ipfsHash)",
  "function setStatus(uint256 agentId, uint8 status)",
  "function isOwner(uint256 agentId, address who) view returns (bool)",
  "function ownerOf(uint256 agentId) view returns (address)",
  "function owner() view returns (address)",
  "function getAgent(uint256 agentId) view returns (tuple(uint256 id, address creator, string ipfsHash, string category, uint8 status, uint256 createdAt, uint256 updatedAt))",
  "function totalAgents() view returns (uint256)",
  "event AgentRegistered(uint256 indexed agentId, address indexed creator, string ipfsHash, string category)",
  "event AgentMetadataUpdated(uint256 indexed agentId, string ipfsHash)",
  "event AgentStatusUpdated(uint256 indexed agentId, uint8 status)",
] as const;

export const VERSION_CONTROL_ABI = [
  "function pushVersion(uint256 agentId, string version, string changelog, string ipfsHash)",
  "function getVersions(uint256 agentId) view returns (tuple(string version, string changelog, string ipfsHash, uint256 publishedAt)[])",
  "function versionCount(uint256 agentId) view returns (uint256)",
  "function latestVersion(uint256 agentId) view returns (tuple(string version, string changelog, string ipfsHash, uint256 publishedAt))",
  "event VersionPublished(uint256 indexed agentId, string version, string ipfsHash, uint256 publishedAt)",
] as const;

export const REPUTATION_ABI = [
  "function getStats(uint256 agentId) view returns (tuple(uint256 completedJobs, uint256 ratingSum, uint256 ratingCount, uint256 uniqueUsers, bool verifiedCreator))",
  "function averageRatingScaled(uint256 agentId) view returns (uint256)",
  "function owner() view returns (address)",
  "function setVerified(uint256 agentId, bool verified)",
  "event VerifiedStatusUpdated(uint256 indexed agentId, bool verified)",
] as const;

export const PAYMENTS_ABI = [
  "function withdrawable(address account) view returns (uint256)",
  "function withdraw()",
  "function feeBps() view returns (uint256)",
  "function feeRecipient() view returns (address)",
  "function owner() view returns (address)",
  "function setFeeBps(uint256 _feeBps)",
  "function setFeeRecipient(address _feeRecipient)",
  "event Withdrawal(address indexed account, uint256 amount)",
  "event PaymentProcessed(uint256 indexed agentId, address indexed payer, address indexed creator, uint256 amount, uint256 fee)",
  "event FeeUpdated(uint256 feeBps)",
] as const;

export const MARKETPLACE_ABI = [
  "function createOrUpdateListing(uint256 agentId, uint8 model, uint256 priceWei, uint32 intervalDays)",
  "function purchase(uint256 agentId) payable",
  "function subscribe(uint256 agentId) payable",
  "function useFreeAgent(uint256 agentId)",
  "function hasActiveAccess(address user, uint256 agentId) view returns (bool)",
  "function getListing(uint256 agentId) view returns (tuple(uint8 model, uint256 priceWei, uint32 intervalDays, bool exists))",
  "event ListingUpdated(uint256 indexed agentId, uint8 model, uint256 priceWei, uint32 intervalDays)",
  "event Purchased(uint256 indexed agentId, address indexed buyer, address indexed creator, uint256 amount, uint8 model)",
  "event Subscribed(uint256 indexed agentId, address indexed subscriber, address indexed creator, uint256 amount, uint256 newExpiry)",
] as const;

export const REVIEW_ABI = [
  "function submitReview(uint256 agentId, uint8 rating, string comment)",
  "function likeReview(uint256 agentId, uint256 index)",
  "function reportReview(uint256 agentId, uint256 index)",
  "function getReviews(uint256 agentId) view returns (tuple(address author, uint8 rating, string comment, uint256 createdAt, uint256 likes, bool reported)[])",
  "function reviewCount(uint256 agentId) view returns (uint256)",
  "function hasReviewed(uint256 agentId, address who) view returns (bool)",
  "function owner() view returns (address)",
  "event ReviewSubmitted(uint256 indexed agentId, address indexed author, uint8 rating, uint256 index)",
  "event ReviewReported(uint256 indexed agentId, uint256 indexed index)",
] as const;

/** Maps `PricingModel` (frontend) <-> `Marketplace.PricingModel` (Solidity enum order). */
export const PRICING_MODEL_TO_ENUM = {
  "one-time": 0,
  subscription: 1,
  free: 2,
  donation: 3,
} as const;

export const PRICING_ENUM_TO_MODEL = ["one-time", "subscription", "free", "donation"] as const;

/** `AgentRegistry.AgentStatus` (Solidity enum order). */
export const STATUS_ENUM_TO_LABEL = ["active", "paused", "unpublished"] as const;
